export enum TodosStoreStatus {
    None,
    GetTodosFetching,
    GetTodosSuccess,
    GetTodosError,
    GetTodoFetching,
    GetTodoSuccess,
    GetTodoError,
    CreateTodoFetching,
    CreateTodoSuccess,
    CreateTodoError,
    UpdateTodoFetching,
    UpdateTodoSuccess,
    UpdateTodoError,
    DeleteTodoFetching,
    DeleteTodoSuccess,
    DeleteTodoError,
}
